

#https-portal:
#  image: steveltn/https-portal:1
#  ports:
#    - 80:80
#    - 443:443
#  links:
#    - djangoapp
#  restart: always
#  environment:
#    DOMAINS: 
#       'short-tips.info -> http://djangoapp:5000, techblog.short-tips.info -> http://techblog.djangoapp:5000'
#    STAGE: production # Don't use production until staging works
#    #FORCE_RENEW: 'true'
#  container_name: https-portal
#  volumes:
#    - ./ssl_certs:/var/lib/https-portal



djangoapp:
  user: root
  build: .
  dockerfile: "Dockerfile"
  environment:
    ENV: DEV
  ports:
   - "80:5000"
  volumes:
    - ./app:/app
    - ./God:/God
  command: ./cmd.sh
  container_name: djangoapp
  #command: python3 manage.py runserver 0.0.0.0:5000 
  links:
    - db



aauto:
  user: root
  build: .
  dockerfile: "Dockerfile-aauto"
  volumes:
    - ./aauto:/aauto
    - ./God:/God
  command: ./cmd.sh
  #command: python3 manage.py runserver 0.0.0.0:5000 
  links:
    - db


db:
  user: root
  image: mariadb
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    MYSQL_ROOT_PASSWORD: rootpw
    MYSQL_DATABASE: stock_database
    MYSQL_USER: user
    MYSQL_PASSWORD: passw0rd
  ports:
    - "3306:3306"
  volumes:
    # 初期データを投入するSQLが格納されているdir
    - ./db/mysql-init:/docker-entrypoint-initdb.d
    # 永続化するときにマウントするdir
    - ./db/mysql-data:/var/lib/mysql
